export ac_cv_func_rename=no

.PHONY: all
all:
#	./configure --prefix=c:/progra~1/Patch

	if ! [ -e makefile.orig ]; then \
	cp -fp makefile makefile.orig; \
	fi
	sed -f makefile.sed makefile.orig >makefile

#	make all
#	make check
#	make install prefix=c:/temp/ed
                                 
